# Generated by Django 3.1.5 on 2021-01-10 17:55

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
